# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import timeline_pb2 as timeline__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in timeline_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TimelineServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTimelineUpdates = channel.stream_unary(
                '/timeline.TimelineService/StreamTimelineUpdates',
                request_serializer=timeline__pb2.TimelineUpdate.SerializeToString,
                response_deserializer=timeline__pb2.TimelineResponse.FromString,
                _registered_method=True)
        self.SendTimelineUpdate = channel.unary_unary(
                '/timeline.TimelineService/SendTimelineUpdate',
                request_serializer=timeline__pb2.TimelineUpdate.SerializeToString,
                response_deserializer=timeline__pb2.TimelineResponse.FromString,
                _registered_method=True)


class TimelineServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamTimelineUpdates(self, request_iterator, context):
        """Stream timeline updates from file agents
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTimelineUpdate(self, request, context):
        """Single timeline update
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TimelineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTimelineUpdates': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamTimelineUpdates,
                    request_deserializer=timeline__pb2.TimelineUpdate.FromString,
                    response_serializer=timeline__pb2.TimelineResponse.SerializeToString,
            ),
            'SendTimelineUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTimelineUpdate,
                    request_deserializer=timeline__pb2.TimelineUpdate.FromString,
                    response_serializer=timeline__pb2.TimelineResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'timeline.TimelineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('timeline.TimelineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TimelineService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamTimelineUpdates(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/timeline.TimelineService/StreamTimelineUpdates',
            timeline__pb2.TimelineUpdate.SerializeToString,
            timeline__pb2.TimelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTimelineUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/timeline.TimelineService/SendTimelineUpdate',
            timeline__pb2.TimelineUpdate.SerializeToString,
            timeline__pb2.TimelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
