# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: timeline.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'timeline.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etimeline.proto\x12\x08timeline\"l\n\x0eTimelineUpdate\x12\x13\n\x0btransfer_id\x18\x01 \x01(\t\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12 \n\x06status\x18\x04 \x01(\x0e\x32\x10.timeline.Status\"4\n\x10TimelineResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t*\x1f\n\x06Status\x12\x0b\n\x07PENDING\x10\x00\x12\x08\n\x04\x44ONE\x10\x01\x32\xae\x01\n\x0fTimelineService\x12O\n\x15StreamTimelineUpdates\x12\x18.timeline.TimelineUpdate\x1a\x1a.timeline.TimelineResponse(\x01\x12J\n\x12SendTimelineUpdate\x12\x18.timeline.TimelineUpdate\x1a\x1a.timeline.TimelineResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'timeline_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS']._serialized_start=192
  _globals['_STATUS']._serialized_end=223
  _globals['_TIMELINEUPDATE']._serialized_start=28
  _globals['_TIMELINEUPDATE']._serialized_end=136
  _globals['_TIMELINERESPONSE']._serialized_start=138
  _globals['_TIMELINERESPONSE']._serialized_end=190
  _globals['_TIMELINESERVICE']._serialized_start=226
  _globals['_TIMELINESERVICE']._serialized_end=400
# @@protoc_insertion_point(module_scope)
